language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

services:
  - couchdb
  - redis-server

addons:
  apt:
    packages:
      - proj-bin
      - libgeos-dev
      - libgdal-dev
      - libxslt1-dev
      - libxml2-dev
      - build-essential
      - python-dev
      - libjpeg-dev
      - zlib1g-dev
      - libfreetype6-dev
      - protobuf-compiler
      - libprotoc-dev

env:
  global:
    - MAPPROXY_TEST_COUCHDB=http://127.0.0.1:5984
    - MAPPROXY_TEST_REDIS=127.0.0.1:6379

    # do not load /etc/boto.cfg with Python 3 incompatible plugin
    # https://github.com/travis-ci/travis-ci/issues/5246#issuecomment-166460882
    - BOTO_CONFIG=/doesnotexist

matrix:
  include:
    # Test 2.7 and 3.8 also with latest Pillow version
    - python: "2.7"
      env: USE_LATEST_PILLOW=1
    - python: "3.8"
      env: USE_LATEST_PILLOW=1

cache:
  directories:
    - $HOME/.cache/pip

install:
    - "pip install -r requirements-tests.txt"
    - "if [[ $USE_LATEST_PILLOW = '1' ]]; then pip install -U Pillow; fi"
    - "pip freeze"

script:
    - pytest mapproxy
